### ISSUE TITLE
All-numeric hostnames should not be valid

### ISSUE THREAD

**Issue by ryheath** [miguelmota/is-valid-hostname#1]
Currently an all-numeric hostname like `10.10.10.10` returns `true`.

This should be `false`, per [RFC 3696](https://tools.ietf.org/html/rfc3696#section-2).

More information here: https://serverfault.com/questions/638260/is-it-valid-for-a-hostname-to-start-with-a-digit

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/is-valid-hostname/pull/2
