### ISSUE TITLE
[Feature request] TypeScript type definitions

### ISSUE THREAD

**Issue by treykasada** [miguelmota/is-valid-hostname#4]
Would be super useful to have these, either as part of the library itself, or on DefinitelyTyped. :slightly_smiling_face:

There actually already seem to be some for your other library `is-valid-domain`: https://www.npmjs.com/package/@types/is-valid-domain

**Comment by miguelmota** [comment]
Types have been added now. See [types/index.d.ts](https://github.com/miguelmota/is-valid-hostname/blob/master/types/index.d.ts)

Closed by https://github.com/miguelmota/is-valid-hostname/commit/fd7e0beb7b2c4c08ca88739a7bab3f3bc1fdded9
