### ISSUE TITLE
How to import types?

### ISSUE THREAD

**Issue by quidcain** [miguelmota/is-valid-hostname#5]
Hi @miguelmota!

First of all thank you for this amazing package. I ran up against an issue of importing the package into a typescript project.
The compiler tells the following
```
Could not find a declaration file for module 'is-valid-hostname'. '/home/daniel/danielproject/node_modules/is-valid-hostname/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/is-valid-hostname` if it exists or add a new declaration (.d.ts) file containing `declare module 'is-valid-hostname';
```

I've tried to add your types both in compilerOptions.typeRoots and compilerOptions.paths like that
```
"compilerOptions": {
  "typeRoots": [
    "node_modules/@types",
    "node_modules/is-valid-hostname/types/*"
  ],
}
```

```
"compilerOptions": {
  "paths": {
    "*": [
      "node_modules/*",
      "node_modules/is-valid-hostname/types/*"
    ]
  },
}
```

I will be very grateful if you can help me

**Comment by quidcain** [comment]
Oh after an hour of relentless trying. I managed to do that.
So I import it like this in my .ts file
```
import isValidHostname from "is-valid-hostname";
```
and I specified the following in the tsconfig.json
```
"compilerOptions": {
  "paths": {
      "is-valid-hostname": [
        "node_modules/is-valid-hostname/types"
      ],
  },
}
```

**Comment by treykasada** [comment]
Ahh, this is because `package.json` is missing a `"types": "types/index.d.ts"` field.

I'll raise a new issue for that.

**Comment by miguelmota** [comment]
Thanks for the bug report @quidcain!

Fixed by https://github.com/miguelmota/is-valid-hostname/commit/71a4e56c81d58d111de97dd05917fb8bb1158652 (Thanks for the suggestion @treykasada)
