### ISSUE TITLE
`package.json` is missing a reference to the TypeScript typings

### ISSUE THREAD

**Issue by treykasada** [miguelmota/is-valid-hostname#6]
Currently, the TypeScript compiler can't find the typings included with this library without users manually referencing them (see #5).

To allow the compiler to find these typings and associate them with the main module, we just need to add
```
"types": "types/index.d.ts",
```
to `package.json`. 🙂

**Comment by miguelmota** [comment]
@treykasada Thanks for the suggestion! The types path is added now and new version is published.

Closed by https://github.com/miguelmota/is-valid-hostname/commit/71a4e56c81d58d111de97dd05917fb8bb1158652
